"""Génère L2_denoising_autoencoder.ipynb à partir de cellules définies en Python."""
from __future__ import annotations
import nbformat as nbf
from pathlib import Path

OUTDIR = Path(__file__).parent


def md(text: str):
    return nbf.v4.new_markdown_cell(text)


def code(src: str):
    return nbf.v4.new_code_cell(src)


cells = [
    md(
        "# Livrable 2 — Débruitage par auto-encodeur convolutionnel\n\n"
        "**Projet TouNum**\n\n"
        "## Objectif\n\n"
        "Construire un **denoising autoencoder (DAE)** convolutif capable de nettoyer "
        "des photographies bruitées issues de la chaîne de numérisation TouNum.\n\n"
        "## Approche\n\n"
        "1. On charge un sous-ensemble de photos propres du dataset.\n"
        "2. On les bruite **artificiellement** (bruit gaussien synthétique).\n"
        "3. On entraîne un autoencodeur à apprendre la transformation `image bruitée -> image propre`.\n"
        "4. On évalue avec des métriques objectives (PSNR, SSIM) et visuellement.\n"
        "5. **Étude de cas** : on mesure l'impact du débruitage sur le classifieur du livrable 1.\n\n"
        "## Pourquoi un autoencodeur ?\n\n"
        "Un autoencodeur apprend à compresser une image dans un espace latent puis à la reconstruire. "
        "Si on lui donne une image **bruitée** en entrée et qu'on lui demande de reproduire l'**originale propre**, "
        "il apprend à filtrer le bruit comme un effet secondaire de la reconstruction. C'est une approche "
        "non-supervisée au sens où on n'a pas besoin d'images réellement bruitées étiquetées — on en fabrique "
        "à la volée."
    ),
    md("## 1. Imports et configuration"),
    code(
        "import json\n"
        "import time\n"
        "from pathlib import Path\n\n"
        "import numpy as np\n"
        "import matplotlib.pyplot as plt\n"
        "import tensorflow as tf\n"
        "from tensorflow.keras import layers, models, callbacks\n"
        "from PIL import Image\n"
        "from skimage.metrics import peak_signal_noise_ratio as psnr_fn\n"
        "from skimage.metrics import structural_similarity as ssim_fn\n\n"
        "# Reproductibilité\n"
        "SEED = 42\n"
        "np.random.seed(SEED)\n"
        "tf.random.set_seed(SEED)\n\n"
        "# Config\n"
        "IMG_SIZE = (128, 128)\n"
        "BATCH_SIZE = 32\n"
        "EPOCHS = 40\n"
        "SIGMA_TRAIN = 0.1   # niveau de bruit pour l'entraînement\n\n"
        "# Chemins\n"
        "SPLIT_DIR = Path('data_split')\n"
        "PHOTO_CLASS = 'Photo'\n"
        "MODELS_DIR = Path('models')\n"
        "HISTORIES_DIR = Path('histories')\n"
        "FIGURES_DIR = Path('figures')\n"
        "for d in [MODELS_DIR, HISTORIES_DIR, FIGURES_DIR]:\n"
        "    d.mkdir(exist_ok=True)\n\n"
        "print('TF :', tf.__version__)\n"
        "print('GPUs :', tf.config.list_physical_devices('GPU'))"
    ),
    md(
        "## 2. Chargement du sous-ensemble Photo\n\n"
        "Le brief précise que le débruitage cible des **photographies**. On utilise donc uniquement le sous-dossier "
        "`Photo/` du split déjà réalisé au livrable 1 (`data_split/`).\n\n"
        "On charge directement en mémoire car le DAE a besoin de paires (entrée_bruitée, sortie_propre) "
        "dans le même ordre, ce qui est plus simple à gérer avec des arrays NumPy qu'avec un generator."
    ),
    code(
        "IMG_EXTENSIONS = {'.jpg', '.jpeg', '.png', '.bmp', '.gif', '.tiff', '.webp'}\n\n"
        "def load_images(directory: Path, img_size=(128, 128), max_images=None) -> np.ndarray:\n"
        "    \"\"\"Charge toutes les images d'un dossier en numpy array (N, H, W, 3) en [0, 1].\"\"\"\n"
        "    paths = [p for p in Path(directory).rglob('*') if p.is_file() and p.suffix.lower() in IMG_EXTENSIONS]\n"
        "    paths = sorted(paths)\n"
        "    if max_images is not None:\n"
        "        paths = paths[:max_images]\n"
        "    images = []\n"
        "    for p in paths:\n"
        "        try:\n"
        "            img = Image.open(p).convert('RGB').resize(img_size, Image.BILINEAR)\n"
        "            images.append(np.asarray(img, dtype=np.float32) / 255.0)\n"
        "        except Exception as e:\n"
        "            print(f'  illisible : {p.name} — {e}')\n"
        "    return np.stack(images) if images else np.empty((0, img_size[1], img_size[0], 3), dtype=np.float32)\n\n"
        "print('Chargement train...')\n"
        "X_train = load_images(SPLIT_DIR / 'train' / PHOTO_CLASS, IMG_SIZE)\n"
        "print('Chargement val...')\n"
        "X_val = load_images(SPLIT_DIR / 'val' / PHOTO_CLASS, IMG_SIZE)\n"
        "print('Chargement test...')\n"
        "X_test = load_images(SPLIT_DIR / 'test' / PHOTO_CLASS, IMG_SIZE)\n\n"
        "print(f'\\nTrain : {X_train.shape}, val : {X_val.shape}, test : {X_test.shape}')\n"
        "print(f'Mémoire train (approx) : {X_train.nbytes / 1e6:.1f} MB')"
    ),
    md("### Visualisation d'exemples propres"),
    code(
        "fig, axes = plt.subplots(2, 5, figsize=(14, 5))\n"
        "for ax, img in zip(axes.flat, X_train[:10]):\n"
        "    ax.imshow(img)\n"
        "    ax.axis('off')\n"
        "plt.suptitle('Photos propres (sample du train set)')\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ),
    md(
        "## 3. Bruitage synthétique\n\n"
        "On ajoute du **bruit gaussien** centré sur 0, d'écart-type `sigma`. C'est le modèle de bruit "
        "le plus courant et le plus étudié — il modélise notamment le bruit thermique des capteurs et "
        "constitue une bonne approximation de pas mal de dégradations réelles.\n\n"
        "**Choix du sigma** :\n"
        "- 0.05 -> bruit léger, à peine perceptible\n"
        "- 0.10 -> bruit modéré, bien visible (notre choix pour l'entraînement)\n"
        "- 0.20 -> bruit fort, image très dégradée\n\n"
        "On utilise `np.clip` après ajout pour rester dans [0, 1]."
    ),
    code(
        "def add_gaussian_noise(x: np.ndarray, sigma: float, seed: int | None = None) -> np.ndarray:\n"
        "    \"\"\"Ajoute du bruit gaussien centré sur 0, std=sigma, et clip dans [0, 1].\"\"\"\n"
        "    rng = np.random.default_rng(seed)\n"
        "    noise = rng.normal(0.0, sigma, size=x.shape).astype(np.float32)\n"
        "    return np.clip(x + noise, 0.0, 1.0)\n\n"
        "# Préparation des données d'entraînement\n"
        "X_train_noisy = add_gaussian_noise(X_train, sigma=SIGMA_TRAIN, seed=SEED)\n"
        "X_val_noisy = add_gaussian_noise(X_val, sigma=SIGMA_TRAIN, seed=SEED + 1)\n"
        "X_test_noisy = add_gaussian_noise(X_test, sigma=SIGMA_TRAIN, seed=SEED + 2)\n\n"
        "print(f'Bruit appliqué (sigma={SIGMA_TRAIN})')\n"
        "print(f'  X_train_noisy : {X_train_noisy.shape}')\n"
        "print(f'  X_val_noisy   : {X_val_noisy.shape}')\n"
        "print(f'  X_test_noisy  : {X_test_noisy.shape}')"
    ),
    md("### Visualisation de la dégradation"),
    code(
        "fig, axes = plt.subplots(2, 5, figsize=(14, 5))\n"
        "for j in range(5):\n"
        "    axes[0, j].imshow(X_train[j])\n"
        "    axes[0, j].set_title('propre')\n"
        "    axes[0, j].axis('off')\n"
        "    axes[1, j].imshow(X_train_noisy[j])\n"
        "    axes[1, j].set_title(f'bruité σ={SIGMA_TRAIN}')\n"
        "    axes[1, j].axis('off')\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ),
    md(
        "## 4. Architecture du DAE convolutionnel\n\n"
        "Architecture **symétrique** classique. L'encodeur réduit progressivement la dimension spatiale "
        "tout en augmentant le nombre de canaux. Le decodeur fait l'inverse via `UpSampling2D`.\n\n"
        "```\n"
        "Input (128, 128, 3)\n"
        "│\n"
        "├─ ENCODER\n"
        "│  Conv(32) BN ReLU\n"
        "│  Conv(32) BN ReLU\n"
        "│  MaxPool(2)            -> (64, 64, 32)\n"
        "│  Conv(64) BN ReLU\n"
        "│  Conv(64) BN ReLU\n"
        "│  MaxPool(2)            -> (32, 32, 64)\n"
        "│  Conv(128) BN ReLU\n"
        "│  Conv(128) BN ReLU\n"
        "│  MaxPool(2)            -> (16, 16, 128)   ← BOTTLENECK\n"
        "│\n"
        "├─ DECODER (symétrique)\n"
        "│  UpSampling(2)\n"
        "│  Conv(64) BN ReLU\n"
        "│  Conv(64) BN ReLU      -> (32, 32, 64)\n"
        "│  UpSampling(2)\n"
        "│  Conv(32) BN ReLU\n"
        "│  Conv(32) BN ReLU      -> (64, 64, 32)\n"
        "│  UpSampling(2)\n"
        "│  Conv(3) sigmoid       -> (128, 128, 3)   ← RECONSTRUCTION\n"
        "```\n\n"
        "**Choix de design** :\n"
        "- **Pas de Dense / Flatten** : on garde tout en convolutif pour respecter la structure spatiale.\n"
        "- **Bottleneck à 16×16×128** : compression d'un facteur ~6 par rapport à l'entrée. Forte assez pour "
        "  forcer le modèle à apprendre une représentation utile, mais pas trop pour ne pas perdre les détails.\n"
        "- **Sigmoid en sortie** : pixels en [0, 1], cohérent avec la normalisation d'entrée.\n"
        "- **BatchNorm partout** : stabilise l'entraînement, surtout important sur les DAE.\n"
        "- **`UpSampling2D`** (nearest-neighbor) suivi de `Conv2D` plutôt que `Conv2DTranspose` : évite les "
        "  artefacts en damier classiques des transposed convolutions.\n\n"
        "**Loss : MSE** (Mean Squared Error) entre la sortie reconstruite et l'image propre. C'est la loss "
        "standard pour la reconstruction d'image. Alternative : MAE (plus robust aux outliers), perceptual loss "
        "(plus coûteux mais plus visuel)."
    ),
    code(
        "def build_dae(img_size=(128, 128)) -> models.Model:\n"
        "    h, w = img_size[1], img_size[0]\n"
        "    inp = layers.Input(shape=(h, w, 3), name='noisy_input')\n\n"
        "    # Encoder\n"
        "    x = layers.Conv2D(32, 3, padding='same', activation='relu')(inp)\n"
        "    x = layers.BatchNormalization()(x)\n"
        "    x = layers.Conv2D(32, 3, padding='same', activation='relu')(x)\n"
        "    x = layers.BatchNormalization()(x)\n"
        "    x = layers.MaxPooling2D(2)(x)\n\n"
        "    x = layers.Conv2D(64, 3, padding='same', activation='relu')(x)\n"
        "    x = layers.BatchNormalization()(x)\n"
        "    x = layers.Conv2D(64, 3, padding='same', activation='relu')(x)\n"
        "    x = layers.BatchNormalization()(x)\n"
        "    x = layers.MaxPooling2D(2)(x)\n\n"
        "    x = layers.Conv2D(128, 3, padding='same', activation='relu')(x)\n"
        "    x = layers.BatchNormalization()(x)\n"
        "    x = layers.Conv2D(128, 3, padding='same', activation='relu')(x)\n"
        "    x = layers.BatchNormalization()(x)\n"
        "    bottleneck = layers.MaxPooling2D(2, name='bottleneck')(x)  # (16, 16, 128)\n\n"
        "    # Decoder\n"
        "    x = layers.UpSampling2D(2)(bottleneck)\n"
        "    x = layers.Conv2D(64, 3, padding='same', activation='relu')(x)\n"
        "    x = layers.BatchNormalization()(x)\n"
        "    x = layers.Conv2D(64, 3, padding='same', activation='relu')(x)\n"
        "    x = layers.BatchNormalization()(x)\n\n"
        "    x = layers.UpSampling2D(2)(x)\n"
        "    x = layers.Conv2D(32, 3, padding='same', activation='relu')(x)\n"
        "    x = layers.BatchNormalization()(x)\n"
        "    x = layers.Conv2D(32, 3, padding='same', activation='relu')(x)\n"
        "    x = layers.BatchNormalization()(x)\n\n"
        "    x = layers.UpSampling2D(2)(x)\n"
        "    out = layers.Conv2D(3, 3, padding='same', activation='sigmoid', name='reconstruction')(x)\n\n"
        "    return models.Model(inp, out, name='denoising_autoencoder')\n\n"
        "dae = build_dae(IMG_SIZE)\n"
        "dae.summary()\n"
        "print(f'\\nTotal params : {dae.count_params():,}')"
    ),
    md("## 5. Compilation\n\nMSE + Adam, classique pour la reconstruction."),
    code(
        "dae.compile(\n"
        "    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),\n"
        "    loss='mse',\n"
        "    metrics=['mae'],\n"
        ")"
    ),
    md(
        "## 6. Entraînement\n\n"
        "On feed `(X_noisy, X_clean)` : le réseau prend en entrée l'image bruitée et la loss est calculée "
        "contre l'image propre. C'est ça la magie : la cible n'est pas un label, c'est l'image elle-même.\n\n"
        "Callbacks : EarlyStopping patience=5 (sur val_loss), ReduceLROnPlateau, ModelCheckpoint."
    ),
    code(
        "MODEL_PATH = MODELS_DIR / 'dae_photo.keras'\n"
        "HISTORY_PATH = HISTORIES_DIR / 'dae_photo_history.json'\n\n"
        "cb = [\n"
        "    callbacks.EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True, verbose=1),\n"
        "    callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, min_lr=1e-6, verbose=1),\n"
        "    callbacks.ModelCheckpoint(str(MODEL_PATH), monitor='val_loss', save_best_only=True, verbose=1),\n"
        "]\n\n"
        "t0 = time.time()\n"
        "history = dae.fit(\n"
        "    X_train_noisy, X_train,\n"
        "    validation_data=(X_val_noisy, X_val),\n"
        "    epochs=EPOCHS,\n"
        "    batch_size=BATCH_SIZE,\n"
        "    callbacks=cb,\n"
        "    verbose=1,\n"
        ")\n"
        "train_time = time.time() - t0\n"
        "print(f'\\nEntraînement terminé en {train_time / 60:.1f} min')\n"
        "print(f'Epochs effectuées : {len(history.history[\"loss\"])}')\n\n"
        "# Sauvegarde history\n"
        "hist_data = {k: [float(v) for v in vals] for k, vals in history.history.items()}\n"
        "with open(HISTORY_PATH, 'w') as f:\n"
        "    json.dump(hist_data, f, indent=2)\n"
        "print(f'History sauvegardée : {HISTORY_PATH}')\n"
        "print(f'Modèle sauvegardé : {MODEL_PATH}')"
    ),
    md("## 7. Courbes d'apprentissage"),
    code(
        "epochs_range = range(1, len(history.history['loss']) + 1)\n"
        "fig, axes = plt.subplots(1, 2, figsize=(14, 4))\n"
        "axes[0].plot(epochs_range, history.history['loss'], label='train loss')\n"
        "axes[0].plot(epochs_range, history.history['val_loss'], label='val loss')\n"
        "axes[0].set_title('MSE')\n"
        "axes[0].set_xlabel('Epoch')\n"
        "axes[0].set_ylabel('MSE')\n"
        "axes[0].legend()\n"
        "axes[0].grid(True, alpha=0.3)\n"
        "axes[1].plot(epochs_range, history.history['mae'], label='train mae')\n"
        "axes[1].plot(epochs_range, history.history['val_mae'], label='val mae')\n"
        "axes[1].set_title('MAE')\n"
        "axes[1].set_xlabel('Epoch')\n"
        "axes[1].set_ylabel('MAE')\n"
        "axes[1].legend()\n"
        "axes[1].grid(True, alpha=0.3)\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ),
    md(
        "## 8. Évaluation visuelle sur le test set\n\n"
        "On compare visuellement : image originale propre / image bruitée / image débruitée par le DAE."
    ),
    code(
        "X_test_denoised = dae.predict(X_test_noisy, batch_size=BATCH_SIZE, verbose=1)\n\n"
        "n_show = 6\n"
        "fig, axes = plt.subplots(3, n_show, figsize=(3 * n_show, 9))\n"
        "for j in range(n_show):\n"
        "    axes[0, j].imshow(X_test[j])\n"
        "    axes[0, j].set_title('originale')\n"
        "    axes[0, j].axis('off')\n"
        "    axes[1, j].imshow(X_test_noisy[j])\n"
        "    axes[1, j].set_title(f'bruitée σ={SIGMA_TRAIN}')\n"
        "    axes[1, j].axis('off')\n"
        "    axes[2, j].imshow(np.clip(X_test_denoised[j], 0, 1))\n"
        "    axes[2, j].set_title('débruitée')\n"
        "    axes[2, j].axis('off')\n"
        "plt.suptitle('Débruitage par DAE — comparaison visuelle')\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ),
    md(
        "## 9. Métriques objectives — PSNR & SSIM\n\n"
        "Pour quantifier la qualité de débruitage, deux métriques standard :\n\n"
        "- **PSNR (Peak Signal-to-Noise Ratio)** : exprimé en dB, plus c'est haut mieux c'est. "
        "  En dessous de 20 dB c'est très moyen, entre 30-40 dB c'est bon, au-dessus de 40 dB c'est excellent.\n"
        "- **SSIM (Structural Similarity)** : entre 0 et 1, mesure la similarité structurelle perçue. "
        "  > 0.9 c'est très bon. SSIM est plus proche de la perception humaine que PSNR.\n\n"
        "On compare : (image bruitée vs originale) vs (image débruitée vs originale). "
        "Si le DAE est utile, les métriques après débruitage doivent être nettement meilleures qu'avant."
    ),
    code(
        "def compute_metrics(originals: np.ndarray, processed: np.ndarray) -> dict:\n"
        "    psnrs, ssims = [], []\n"
        "    for orig, proc in zip(originals, processed):\n"
        "        proc_clipped = np.clip(proc, 0, 1)\n"
        "        psnrs.append(psnr_fn(orig, proc_clipped, data_range=1.0))\n"
        "        ssims.append(ssim_fn(orig, proc_clipped, data_range=1.0, channel_axis=-1))\n"
        "    return {\n"
        "        'psnr_mean': float(np.mean(psnrs)),\n"
        "        'psnr_std': float(np.std(psnrs)),\n"
        "        'ssim_mean': float(np.mean(ssims)),\n"
        "        'ssim_std': float(np.std(ssims)),\n"
        "    }\n\n"
        "metrics_noisy = compute_metrics(X_test, X_test_noisy)\n"
        "metrics_denoised = compute_metrics(X_test, X_test_denoised)\n\n"
        "print(f'AVANT débruitage (image bruitée vs originale) :')\n"
        "print(f'  PSNR : {metrics_noisy[\"psnr_mean\"]:.2f} ± {metrics_noisy[\"psnr_std\"]:.2f} dB')\n"
        "print(f'  SSIM : {metrics_noisy[\"ssim_mean\"]:.4f} ± {metrics_noisy[\"ssim_std\"]:.4f}')\n"
        "print(f'\\nAPRÈS débruitage par DAE :')\n"
        "print(f'  PSNR : {metrics_denoised[\"psnr_mean\"]:.2f} ± {metrics_denoised[\"psnr_std\"]:.2f} dB')\n"
        "print(f'  SSIM : {metrics_denoised[\"ssim_mean\"]:.4f} ± {metrics_denoised[\"ssim_std\"]:.4f}')\n\n"
        "gain_psnr = metrics_denoised['psnr_mean'] - metrics_noisy['psnr_mean']\n"
        "gain_ssim = metrics_denoised['ssim_mean'] - metrics_noisy['ssim_mean']\n"
        "print(f'\\nGain PSNR : {gain_psnr:+.2f} dB')\n"
        "print(f'Gain SSIM : {gain_ssim:+.4f}')"
    ),
    md(
        "## 10. Étude de cas — robustesse à différents niveaux de bruit\n\n"
        "Le DAE a été entraîné sur du bruit σ=0.1. Comment se comporte-t-il sur des images bruitées "
        "**plus ou moins fort** ? C'est important : en production, on ne contrôle pas le niveau de bruit "
        "des images entrantes."
    ),
    code(
        "sigmas_test = [0.05, 0.10, 0.15, 0.20, 0.30]\n"
        "study = []\n"
        "for sigma in sigmas_test:\n"
        "    X_noisy_s = add_gaussian_noise(X_test, sigma=sigma, seed=SEED + int(sigma * 1000))\n"
        "    X_denoised_s = dae.predict(X_noisy_s, batch_size=BATCH_SIZE, verbose=0)\n"
        "    m_noisy = compute_metrics(X_test, X_noisy_s)\n"
        "    m_denoised = compute_metrics(X_test, X_denoised_s)\n"
        "    study.append({\n"
        "        'sigma': sigma,\n"
        "        'psnr_noisy': m_noisy['psnr_mean'],\n"
        "        'psnr_denoised': m_denoised['psnr_mean'],\n"
        "        'gain_psnr': m_denoised['psnr_mean'] - m_noisy['psnr_mean'],\n"
        "        'ssim_noisy': m_noisy['ssim_mean'],\n"
        "        'ssim_denoised': m_denoised['ssim_mean'],\n"
        "        'gain_ssim': m_denoised['ssim_mean'] - m_noisy['ssim_mean'],\n"
        "    })\n\n"
        "import pandas as pd\n"
        "df_study = pd.DataFrame(study)\n"
        "df_study"
    ),
    code(
        "fig, axes = plt.subplots(1, 2, figsize=(14, 4))\n"
        "axes[0].plot(df_study['sigma'], df_study['psnr_noisy'], 'o-', label='bruité (avant)')\n"
        "axes[0].plot(df_study['sigma'], df_study['psnr_denoised'], 's-', label='débruité (après DAE)')\n"
        "axes[0].axvline(SIGMA_TRAIN, color='gray', linestyle='--', alpha=0.5, label=f'σ entraînement={SIGMA_TRAIN}')\n"
        "axes[0].set_xlabel('Sigma (niveau de bruit)')\n"
        "axes[0].set_ylabel('PSNR (dB)')\n"
        "axes[0].set_title('PSNR vs niveau de bruit')\n"
        "axes[0].legend()\n"
        "axes[0].grid(True, alpha=0.3)\n\n"
        "axes[1].plot(df_study['sigma'], df_study['ssim_noisy'], 'o-', label='bruité (avant)')\n"
        "axes[1].plot(df_study['sigma'], df_study['ssim_denoised'], 's-', label='débruité (après DAE)')\n"
        "axes[1].axvline(SIGMA_TRAIN, color='gray', linestyle='--', alpha=0.5, label=f'σ entraînement={SIGMA_TRAIN}')\n"
        "axes[1].set_xlabel('Sigma (niveau de bruit)')\n"
        "axes[1].set_ylabel('SSIM')\n"
        "axes[1].set_title('SSIM vs niveau de bruit')\n"
        "axes[1].legend()\n"
        "axes[1].grid(True, alpha=0.3)\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ),
    md("### Visualisation à différents niveaux"),
    code(
        "n_examples = 3  # nb d'images à montrer\n"
        "fig, axes = plt.subplots(len(sigmas_test), n_examples * 2 + 1, figsize=(18, 3 * len(sigmas_test)))\n"
        "for i, sigma in enumerate(sigmas_test):\n"
        "    X_noisy_s = add_gaussian_noise(X_test, sigma=sigma, seed=SEED + i)\n"
        "    X_denoised_s = dae.predict(X_noisy_s[:n_examples], verbose=0)\n"
        "    for j in range(n_examples):\n"
        "        axes[i, 0].set_ylabel(f'σ={sigma}', fontsize=11, rotation=0, labelpad=30)\n"
        "        axes[i, 2 * j].imshow(X_noisy_s[j])\n"
        "        axes[i, 2 * j].set_title('bruité' if i == 0 else '')\n"
        "        axes[i, 2 * j].set_xticks([])\n"
        "        axes[i, 2 * j].set_yticks([])\n"
        "        axes[i, 2 * j + 1].imshow(np.clip(X_denoised_s[j], 0, 1))\n"
        "        axes[i, 2 * j + 1].set_title('débruité' if i == 0 else '')\n"
        "        axes[i, 2 * j + 1].set_xticks([])\n"
        "        axes[i, 2 * j + 1].set_yticks([])\n"
        "    axes[i, -1].imshow(X_test[0])\n"
        "    axes[i, -1].set_title('original' if i == 0 else '')\n"
        "    axes[i, -1].set_xticks([])\n"
        "    axes[i, -1].set_yticks([])\n"
        "plt.suptitle('Débruitage à différents niveaux de bruit')\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ),
    md(
        "## 11. Étude de cas — impact sur le classifieur du livrable 1\n\n"
        "**Le test killer** : on prend les images bruitées du test set, on les classifie **sans débruitage** puis "
        "**avec débruitage par le DAE**, et on compare l'accuracy. Si le DAE fait son boulot, il doit "
        "*restaurer* la performance du classifieur dégradée par le bruit.\n\n"
        "Cette section nécessite que le modèle `multiclass_best.keras` du livrable 1 existe dans `models/`. "
        "Si tu n'as pas encore entraîné le livrable 1, tu peux skip cette section."
    ),
    code(
        "MULTICLASS_PATH = MODELS_DIR / 'multiclass_best.keras'\n\n"
        "if not MULTICLASS_PATH.exists():\n"
        "    print(f'Modèle classifieur introuvable : {MULTICLASS_PATH}')\n"
        "    print('Skip de l\\'étude de cas — entraîne d\\'abord le livrable 1 puis re-run.')\n"
        "    SKIP_CLASSIFIER_STUDY = True\n"
        "else:\n"
        "    classifier = tf.keras.models.load_model(MULTICLASS_PATH)\n"
        "    print(f'Classifieur chargé : {classifier.count_params():,} params')\n"
        "    SKIP_CLASSIFIER_STUDY = False"
    ),
    code(
        "if not SKIP_CLASSIFIER_STUDY:\n"
        "    # Pour comparaison juste, on charge TOUT le test set (5 classes, pas que Photo)\n"
        "    # afin de mesurer l'accuracy multi-class globale.\n"
        "    CLASS_NAMES = sorted([d.name for d in (SPLIT_DIR / 'test').iterdir() if d.is_dir()])\n"
        "    print('Classes :', CLASS_NAMES)\n\n"
        "    print('\\nChargement du test set complet (5 classes)...')\n"
        "    X_test_full, y_test_full = [], []\n"
        "    for idx, c in enumerate(CLASS_NAMES):\n"
        "        imgs = load_images(SPLIT_DIR / 'test' / c, IMG_SIZE)\n"
        "        X_test_full.append(imgs)\n"
        "        y_test_full.extend([idx] * len(imgs))\n"
        "        print(f'  {c:12s} : {len(imgs)}')\n"
        "    X_test_full = np.concatenate(X_test_full, axis=0)\n"
        "    y_test_full = np.array(y_test_full)\n"
        "    print(f'Total : {len(X_test_full)} images')"
    ),
    code(
        "if not SKIP_CLASSIFIER_STUDY:\n"
        "    sigmas_for_classifier = [0.0, 0.05, 0.10, 0.20, 0.30]\n"
        "    classifier_study = []\n\n"
        "    for sigma in sigmas_for_classifier:\n"
        "        if sigma == 0.0:\n"
        "            X_noisy_full = X_test_full\n"
        "        else:\n"
        "            X_noisy_full = add_gaussian_noise(X_test_full, sigma=sigma, seed=SEED + int(sigma * 100))\n\n"
        "        # accuracy classifier sur images bruitées (sans débruitage)\n"
        "        preds_noisy = classifier.predict(X_noisy_full, batch_size=BATCH_SIZE, verbose=0).argmax(axis=1)\n"
        "        acc_noisy = (preds_noisy == y_test_full).mean()\n\n"
        "        # accuracy classifier sur images débruitées par DAE\n"
        "        if sigma == 0.0:\n"
        "            X_denoised_full = X_noisy_full  # rien à débruiter\n"
        "            acc_denoised = acc_noisy\n"
        "        else:\n"
        "            X_denoised_full = dae.predict(X_noisy_full, batch_size=BATCH_SIZE, verbose=0)\n"
        "            X_denoised_full = np.clip(X_denoised_full, 0, 1)\n"
        "            preds_denoised = classifier.predict(X_denoised_full, batch_size=BATCH_SIZE, verbose=0).argmax(axis=1)\n"
        "            acc_denoised = (preds_denoised == y_test_full).mean()\n\n"
        "        classifier_study.append({\n"
        "            'sigma': sigma,\n"
        "            'acc_brut': acc_noisy,\n"
        "            'acc_avec_DAE': acc_denoised,\n"
        "            'gain': acc_denoised - acc_noisy,\n"
        "        })\n\n"
        "    df_clf = pd.DataFrame(classifier_study)\n"
        "    print(df_clf.to_string(index=False))"
    ),
    code(
        "if not SKIP_CLASSIFIER_STUDY:\n"
        "    fig, ax = plt.subplots(figsize=(9, 5))\n"
        "    ax.plot(df_clf['sigma'], df_clf['acc_brut'], 'o-', label='Classifieur direct sur image bruitée', linewidth=2)\n"
        "    ax.plot(df_clf['sigma'], df_clf['acc_avec_DAE'], 's-', label='DAE -> classifieur', linewidth=2)\n"
        "    ax.set_xlabel('Sigma (bruit en entrée)')\n"
        "    ax.set_ylabel('Accuracy classification (5 classes)')\n"
        "    ax.set_title('Impact du débruitage sur la performance du classifieur')\n"
        "    ax.legend()\n"
        "    ax.grid(True, alpha=0.3)\n"
        "    plt.tight_layout()\n"
        "    plt.show()"
    ),
    md(
        "## 12. Conclusions et discussion\n\n"
        "**Résultats à remplir après run** :\n"
        "- Le DAE améliore le PSNR de … dB et le SSIM de … sur le test set au niveau de bruit d'entraînement (σ=0.1).\n"
        "- Le modèle généralise … bien à des niveaux de bruit non vus pendant l'entraînement (cf §10).\n"
        "- Sur le classifieur du livrable 1, le débruitage permet de récupérer … points d'accuracy à σ=0.2 "
        "  (où le classifieur seul chute à …%).\n\n"
        "**Choix techniques et leurs justifications** :\n"
        "- **Architecture symétrique sans skip connection** : choix simple et lisible. Pour aller plus loin, "
        "  un **U-Net** avec skip connections preserve mieux les détails fins (recommandé en extension).\n"
        "- **UpSampling + Conv plutôt que Conv2DTranspose** : évite les artefacts en damier.\n"
        "- **MSE** comme loss : standard, mais a tendance à produire des images légèrement floues. "
        "  Alternatives : MAE (plus net), ou perceptual loss basée sur les features d'un VGG pré-entraîné.\n"
        "- **BatchNorm partout** : stabilise l'entraînement.\n"
        "- **Bruit gaussien synthétique** : couvre la majorité des cas réels. Pour des dégradations plus "
        "  spécifiques (flou de bougé, compression JPEG, lignes de scan), il faudrait entraîner sur ces "
        "  types de bruit aussi.\n\n"
        "**Limites identifiées** :\n"
        "- Le DAE est entraîné sur des Photos uniquement. Sur d'autres classes (Painting, Schematics…) il "
        "  pourrait moins bien marcher car il a appris la distribution statistique des photos.\n"
        "- Le bruit synthétique gaussien ne couvre pas toutes les dégradations réelles (artefacts JPEG, "
        "  lignes de scan, taches…).\n"
        "- Sur très fort bruit (σ > 0.2), le DAE perd les détails fins et produit des images lisses mais "
        "  imprécises.\n\n"
        "**Pistes d'amélioration** :\n"
        "- Passer à une **architecture U-Net** avec skip connections (gain typique +3-5 dB PSNR).\n"
        "- Entraîner sur un **mix de plusieurs types de bruit** (gaussien + sel/poivre + flou + JPEG).\n"
        "- **Perceptual loss** au lieu de MSE pour des résultats plus nets visuellement.\n"
        "- **Étendre à toutes les classes du dataset**, pas juste Photo, pour un DAE généraliste.\n"
        "- **Évaluer sur de vraies images dégradées** quand TouNum en fournira."
    ),
]


if __name__ == '__main__':
    nb = nbf.v4.new_notebook()
    nb.cells = cells
    nb.metadata = {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10"},
    }
    path = OUTDIR / 'L2_denoising_autoencoder.ipynb'
    with open(path, 'w', encoding='utf-8') as f:
        nbf.write(nb, f)
    print(f'Écrit : {path}')
