"""Régénère L2_super_resolution.ipynb (approche super-résolution, U-Net)."""
from __future__ import annotations
import nbformat as nbf
from pathlib import Path

OUTDIR = Path(__file__).parent


def md(text): return nbf.v4.new_markdown_cell(text)
def code(src): return nbf.v4.new_code_cell(src)


cells = [
    md(
        "# Livrable 2 — Restauration / super-résolution par autoencodeur convolutif\n\n"
        "**Projet TouNum**\n\n"
        "## Contexte\n\n"
        "Le dataset livrable 2 contient des photographies dont la **résolution est faible** (et c'est ça notre forme "
        "de 'bruit' : la perte de détail due à une numérisation basse qualité). L'objectif est d'entraîner un "
        "autoencodeur convolutif capable d'**améliorer la qualité** de ces images.\n\n"
        "## Difficulté\n\n"
        "On n'a **pas** de versions haute-résolution de référence — uniquement les images déjà dégradées. Impossible "
        "donc d'entraîner directement un modèle `dégradée -> propre` avec supervision classique.\n\n"
        "## Stratégie : auto-supervision par dégradation synthétique\n\n"
        "On utilise une approche dite *self-supervised* :\n\n"
        "1. On prend les images du dataset (qu'on considère comme nos 'meilleures références disponibles').\n"
        "2. On les **dégrade encore plus** par downsampling agressif + upsampling bilinéaire (perte volontaire de détails).\n"
        "3. On entraîne l'autoencodeur sur les paires `(version_super_dégradée, version_originale)`.\n"
        "4. Le modèle apprend à **inverser** la dégradation — il devient un restaurateur de résolution.\n"
        "5. À l'inférence, on lui donne les originales : il fait de son mieux pour restaurer encore plus de détails "
        "qu'il n'en voit.\n\n"
        "C'est la même idée qui sous-tend des modèles modernes comme **BSRGAN** ou **Real-ESRGAN** : on simule la "
        "dégradation pour apprendre à l'inverser.\n\n"
        "## Architecture : U-Net (autoencodeur avec skip connections)\n\n"
        "Pour la restauration d'image, un autoencodeur classique **sans** skip connections produit des sorties floues "
        "(la compression au bottleneck perd les hautes fréquences spatiales). Le **U-Net** corrige ça en passant "
        "directement les feature maps de l'encodeur vers le décodeur via des skip connections. Résultat : on garde "
        "les détails fins. C'est l'architecture standard pour la restauration d'image."
    ),
    md("## 1. Imports et configuration"),
    code(
        "import json\n"
        "import random\n"
        "import time\n"
        "from pathlib import Path\n\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "import matplotlib.pyplot as plt\n"
        "import tensorflow as tf\n"
        "from tensorflow.keras import layers, models, callbacks\n"
        "from PIL import Image\n"
        "from skimage.metrics import peak_signal_noise_ratio as psnr_fn\n"
        "from skimage.metrics import structural_similarity as ssim_fn\n\n"
        "# Reproductibilité\n"
        "SEED = 42\n"
        "random.seed(SEED)\n"
        "np.random.seed(SEED)\n"
        "tf.random.set_seed(SEED)\n\n"
        "# Configuration\n"
        "IMG_SIZE = (128, 128)            # H, W\n"
        "BATCH_SIZE = 16\n"
        "EPOCHS = 60\n"
        "DOWNSCALE_FACTOR_TRAIN = 4       # divise par 4 puis remonte : perte forte de détails\n\n"
        "# Chemins (adapte si ta structure est différente)\n"
        "DATASET_L2 = Path('Dataset/Dataset/Dataset Livrable2/Dataset')\n"
        "MODELS_DIR = Path('models')\n"
        "HISTORIES_DIR = Path('histories')\n"
        "FIGURES_DIR = Path('figures')\n"
        "for d in [MODELS_DIR, HISTORIES_DIR, FIGURES_DIR]:\n"
        "    d.mkdir(exist_ok=True)\n\n"
        "print('TF :', tf.__version__)\n"
        "print('GPUs :', tf.config.list_physical_devices('GPU'))\n"
        "print('Dataset L2 :', DATASET_L2.resolve())\n"
        "print('Existe ?', DATASET_L2.exists())"
    ),
    md(
        "## 2. Chargement du dataset livrable 2\n\n"
        "Toutes les images sont dans le même dossier (pas de sous-dossiers de classes). On les charge "
        "en mémoire, redimensionnées en `IMG_SIZE`. Ce sera nos **références** d'entraînement."
    ),
    code(
        "IMG_EXT = {'.jpg', '.jpeg', '.png', '.bmp', '.tiff', '.webp'}\n\n"
        "def load_images(directory: Path, img_size=(128, 128), max_images=None) -> np.ndarray:\n"
        "    paths = sorted(p for p in Path(directory).rglob('*')\n"
        "                   if p.is_file() and p.suffix.lower() in IMG_EXT)\n"
        "    if max_images:\n"
        "        paths = paths[:max_images]\n"
        "    images = []\n"
        "    for p in paths:\n"
        "        try:\n"
        "            img = Image.open(p).convert('RGB').resize(img_size, Image.BILINEAR)\n"
        "            images.append(np.asarray(img, dtype=np.float32) / 255.0)\n"
        "        except Exception as e:\n"
        "            print(f'illisible : {p.name} — {e}')\n"
        "    if not images:\n"
        "        return np.empty((0, img_size[1], img_size[0], 3), dtype=np.float32)\n"
        "    return np.stack(images)\n\n"
        "print('Chargement en cours...')\n"
        "t0 = time.time()\n"
        "X_all = load_images(DATASET_L2, IMG_SIZE)\n"
        "print(f'Chargé en {time.time() - t0:.1f}s : {X_all.shape}')\n"
        "print(f'Mémoire : {X_all.nbytes / 1e6:.1f} MB')"
    ),
    md("### Exemples du dataset"),
    code(
        "n = min(10, len(X_all))\n"
        "fig, axes = plt.subplots(2, 5, figsize=(14, 5))\n"
        "for ax, img in zip(axes.flat, X_all[:n]):\n"
        "    ax.imshow(img); ax.axis('off')\n"
        "plt.suptitle('Échantillon du dataset livrable 2 (déjà basse résolution)')\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ),
    md(
        "## 3. Split train / val / test (inline 80/10/10)\n\n"
        "Pas besoin de dossiers physiques cette fois — on shuffle et on découpe les indices."
    ),
    code(
        "rng = np.random.RandomState(SEED)\n"
        "indices = rng.permutation(len(X_all))\n"
        "n = len(indices)\n"
        "n_train = int(n * 0.80)\n"
        "n_val = int(n * 0.10)\n"
        "idx_train = indices[:n_train]\n"
        "idx_val = indices[n_train:n_train + n_val]\n"
        "idx_test = indices[n_train + n_val:]\n\n"
        "X_train = X_all[idx_train]\n"
        "X_val = X_all[idx_val]\n"
        "X_test = X_all[idx_test]\n\n"
        "print(f'Train : {X_train.shape}')\n"
        "print(f'Val   : {X_val.shape}')\n"
        "print(f'Test  : {X_test.shape}')"
    ),
    md(
        "## 4. Fonction de dégradation synthétique\n\n"
        "On simule une perte de résolution forte :\n\n"
        "1. Downsample par un facteur k (BICUBIC ou BILINEAR)\n"
        "2. Upsample à la taille d'origine par BILINEAR (flou caractéristique)\n\n"
        "Plus le facteur est grand, plus l'image est dégradée. On utilise **k=4** pour l'entraînement "
        "(divise la résolution effective par 4)."
    ),
    code(
        "def degrade_resolution(x: np.ndarray, factor: int = 4) -> np.ndarray:\n"
        "    \"\"\"Downsample par `factor` puis upsample bilinéaire à la taille d'origine.\n\n"
        "    Accepte un array (N, H, W, 3) ou (H, W, 3), valeurs en [0, 1].\"\"\"\n"
        "    single = (x.ndim == 3)\n"
        "    if single:\n"
        "        x = x[None]\n"
        "    out = []\n"
        "    for img in x:\n"
        "        h, w = img.shape[:2]\n"
        "        small_h, small_w = max(1, h // factor), max(1, w // factor)\n"
        "        pil = Image.fromarray((img * 255).clip(0, 255).astype(np.uint8))\n"
        "        small = pil.resize((small_w, small_h), Image.BILINEAR)\n"
        "        back = small.resize((w, h), Image.BILINEAR)\n"
        "        out.append(np.asarray(back, dtype=np.float32) / 255.0)\n"
        "    out = np.stack(out)\n"
        "    return out[0] if single else out\n\n"
        "# Préparation des paires d'entraînement\n"
        "print(f'Dégradation par facteur {DOWNSCALE_FACTOR_TRAIN}...')\n"
        "X_train_lo = degrade_resolution(X_train, DOWNSCALE_FACTOR_TRAIN)\n"
        "X_val_lo = degrade_resolution(X_val, DOWNSCALE_FACTOR_TRAIN)\n"
        "X_test_lo = degrade_resolution(X_test, DOWNSCALE_FACTOR_TRAIN)\n"
        "print('OK')"
    ),
    md("### Visualisation : original vs dégradé synthétique"),
    code(
        "n = 5\n"
        "fig, axes = plt.subplots(2, n, figsize=(3 * n, 6))\n"
        "for j in range(n):\n"
        "    axes[0, j].imshow(X_train[j]); axes[0, j].set_title('original'); axes[0, j].axis('off')\n"
        "    axes[1, j].imshow(X_train_lo[j]); axes[1, j].set_title(f'dégradé ÷{DOWNSCALE_FACTOR_TRAIN}'); axes[1, j].axis('off')\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ),
    md(
        "## 5. Architecture U-Net\n\n"
        "Encodeur descendant + décodeur remontant avec **skip connections** entre niveaux symétriques.\n\n"
        "```\n"
        "                                              skip ─────────────────────────────────┐\n"
        "Input (128,128,3) -> Conv-BN-Conv-BN (32) ─────────────────────────────── + -> Conv  -> Output\n"
        "                          │ MaxPool                                            ▲\n"
        "                          ▼                                                    │\n"
        "                       (64,64,32) -> Conv-BN-Conv-BN (64) ─── skip ──────────── +\n"
        "                                          │ MaxPool                            ▲\n"
        "                                          ▼                                    │\n"
        "                                       (32,32,64) -> Conv-BN-Conv-BN (128) ──── + skip\n"
        "                                                         │ MaxPool             ▲\n"
        "                                                         ▼                     │\n"
        "                                                      (16,16,128) ←  bottleneck (256)\n"
        "                                                                       │\n"
        "                                                                       upsample\n"
        "```\n\n"
        "Les skip connections permettent au décodeur de récupérer les détails spatiaux fins de l'encodeur sans "
        "avoir à les reconstruire depuis le bottleneck (impossible mathématiquement à reconstruire parfaitement)."
    ),
    code(
        "def conv_block(x, filters):\n"
        "    x = layers.Conv2D(filters, 3, padding='same')(x)\n"
        "    x = layers.BatchNormalization()(x)\n"
        "    x = layers.ReLU()(x)\n"
        "    x = layers.Conv2D(filters, 3, padding='same')(x)\n"
        "    x = layers.BatchNormalization()(x)\n"
        "    x = layers.ReLU()(x)\n"
        "    return x\n\n"
        "def build_unet(img_size=(128, 128)) -> models.Model:\n"
        "    h, w = img_size[1], img_size[0]\n"
        "    inp = layers.Input(shape=(h, w, 3), name='low_res_input')\n\n"
        "    # Encoder\n"
        "    c1 = conv_block(inp, 32)        # (128, 128, 32)\n"
        "    p1 = layers.MaxPooling2D(2)(c1)\n"
        "    c2 = conv_block(p1, 64)         # (64, 64, 64)\n"
        "    p2 = layers.MaxPooling2D(2)(c2)\n"
        "    c3 = conv_block(p2, 128)        # (32, 32, 128)\n"
        "    p3 = layers.MaxPooling2D(2)(c3)\n\n"
        "    # Bottleneck\n"
        "    b = conv_block(p3, 256)         # (16, 16, 256)\n\n"
        "    # Decoder avec skip connections\n"
        "    u3 = layers.UpSampling2D(2)(b)                        # (32, 32, 256)\n"
        "    u3 = layers.Concatenate()([u3, c3])                   # (32, 32, 256+128)\n"
        "    d3 = conv_block(u3, 128)\n\n"
        "    u2 = layers.UpSampling2D(2)(d3)                       # (64, 64, 128)\n"
        "    u2 = layers.Concatenate()([u2, c2])                   # (64, 64, 128+64)\n"
        "    d2 = conv_block(u2, 64)\n\n"
        "    u1 = layers.UpSampling2D(2)(d2)                       # (128, 128, 64)\n"
        "    u1 = layers.Concatenate()([u1, c1])                   # (128, 128, 64+32)\n"
        "    d1 = conv_block(u1, 32)\n\n"
        "    out = layers.Conv2D(3, 1, activation='sigmoid', name='restored')(d1)\n"
        "    return models.Model(inp, out, name='unet_super_resolution')\n\n"
        "unet = build_unet(IMG_SIZE)\n"
        "unet.summary()\n"
        "print(f'\\nTotal params : {unet.count_params():,}')"
    ),
    md(
        "## 6. Compilation\n\n"
        "- **Loss : MSE** (Mean Squared Error). Standard pour la reconstruction.\n"
        "- **Optimiseur : Adam** lr=1e-3.\n"
        "- **Métrique : MAE**.\n\n"
        "Note : la MSE produit parfois des résultats légèrement flous (moyenne pixel par pixel). "
        "Alternatives possibles : MAE pure, ou perceptual loss VGG (plus net mais plus complexe)."
    ),
    code(
        "unet.compile(\n"
        "    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),\n"
        "    loss='mse',\n"
        "    metrics=['mae'],\n"
        ")"
    ),
    md(
        "## 7. Entraînement\n\n"
        "On feed `(X_train_lo, X_train)` : entrée = version dégradée, cible = original. "
        "Le réseau apprend à restaurer les détails perdus.\n\n"
        "Callbacks : EarlyStopping patience=8 (plus permissif que pour la classification, la SR met plus longtemps "
        "à converger), ReduceLROnPlateau, ModelCheckpoint."
    ),
    code(
        "MODEL_PATH = MODELS_DIR / 'unet_sr.keras'\n"
        "HISTORY_PATH = HISTORIES_DIR / 'unet_sr_history.json'\n\n"
        "cb = [\n"
        "    callbacks.EarlyStopping(monitor='val_loss', patience=8, restore_best_weights=True, verbose=1),\n"
        "    callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=4, min_lr=1e-6, verbose=1),\n"
        "    callbacks.ModelCheckpoint(str(MODEL_PATH), monitor='val_loss', save_best_only=True, verbose=1),\n"
        "]\n\n"
        "t_start = time.time()\n"
        "history = unet.fit(\n"
        "    X_train_lo, X_train,\n"
        "    validation_data=(X_val_lo, X_val),\n"
        "    epochs=EPOCHS,\n"
        "    batch_size=BATCH_SIZE,\n"
        "    callbacks=cb,\n"
        "    verbose=1,\n"
        ")\n"
        "print(f'\\nEntraînement : {(time.time() - t_start) / 60:.1f} min — {len(history.history[\"loss\"])} epochs')\n\n"
        "hist_data = {k: [float(v) for v in vals] for k, vals in history.history.items()}\n"
        "with open(HISTORY_PATH, 'w') as f:\n"
        "    json.dump(hist_data, f, indent=2)\n"
        "print(f'History : {HISTORY_PATH}')\n"
        "print(f'Modèle  : {MODEL_PATH}')"
    ),
    md("## 8. Courbes d'apprentissage"),
    code(
        "epochs_range = range(1, len(history.history['loss']) + 1)\n"
        "fig, axes = plt.subplots(1, 2, figsize=(14, 4))\n"
        "axes[0].plot(epochs_range, history.history['loss'], label='train')\n"
        "axes[0].plot(epochs_range, history.history['val_loss'], label='val')\n"
        "axes[0].set_title('MSE'); axes[0].set_xlabel('Epoch'); axes[0].legend(); axes[0].grid(True, alpha=0.3)\n"
        "axes[1].plot(epochs_range, history.history['mae'], label='train')\n"
        "axes[1].plot(epochs_range, history.history['val_mae'], label='val')\n"
        "axes[1].set_title('MAE'); axes[1].set_xlabel('Epoch'); axes[1].legend(); axes[1].grid(True, alpha=0.3)\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ),
    md(
        "## 9. Évaluation visuelle — paires synthétiques\n\n"
        "On compare : `original | version dégradée (entrée du modèle) | reconstruction par U-Net`. "
        "Le modèle doit essayer de retrouver le contenu de la 1re colonne en partant de la 2e."
    ),
    code(
        "X_test_restored = unet.predict(X_test_lo, batch_size=BATCH_SIZE, verbose=1)\n\n"
        "n = 6\n"
        "fig, axes = plt.subplots(n, 3, figsize=(10, 3 * n))\n"
        "for i in range(n):\n"
        "    axes[i, 0].imshow(X_test[i]); axes[i, 0].set_title('original'); axes[i, 0].axis('off')\n"
        "    axes[i, 1].imshow(X_test_lo[i]); axes[i, 1].set_title(f'dégradé ÷{DOWNSCALE_FACTOR_TRAIN}'); axes[i, 1].axis('off')\n"
        "    axes[i, 2].imshow(np.clip(X_test_restored[i], 0, 1)); axes[i, 2].set_title('restauré (U-Net)'); axes[i, 2].axis('off')\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ),
    md(
        "## 10. Métriques PSNR / SSIM\n\n"
        "Pour quantifier le gain :\n"
        "- (image dégradée vs originale) -> baseline avant débruitage\n"
        "- (image restaurée par U-Net vs originale) -> après débruitage\n"
        "Un bon modèle doit faire monter le PSNR et le SSIM."
    ),
    code(
        "def compute_metrics(originals, processed):\n"
        "    psnrs, ssims = [], []\n"
        "    for orig, proc in zip(originals, processed):\n"
        "        proc = np.clip(proc, 0, 1)\n"
        "        psnrs.append(psnr_fn(orig, proc, data_range=1.0))\n"
        "        ssims.append(ssim_fn(orig, proc, data_range=1.0, channel_axis=-1))\n"
        "    return {\n"
        "        'psnr_mean': float(np.mean(psnrs)),\n"
        "        'psnr_std': float(np.std(psnrs)),\n"
        "        'ssim_mean': float(np.mean(ssims)),\n"
        "        'ssim_std': float(np.std(ssims)),\n"
        "    }\n\n"
        "m_degraded = compute_metrics(X_test, X_test_lo)\n"
        "m_restored = compute_metrics(X_test, X_test_restored)\n\n"
        "print('AVANT restauration (dégradé vs original)')\n"
        "print(f'  PSNR : {m_degraded[\"psnr_mean\"]:.2f} ± {m_degraded[\"psnr_std\"]:.2f} dB')\n"
        "print(f'  SSIM : {m_degraded[\"ssim_mean\"]:.4f} ± {m_degraded[\"ssim_std\"]:.4f}')\n"
        "print('APRÈS restauration (U-Net vs original)')\n"
        "print(f'  PSNR : {m_restored[\"psnr_mean\"]:.2f} ± {m_restored[\"psnr_std\"]:.2f} dB')\n"
        "print(f'  SSIM : {m_restored[\"ssim_mean\"]:.4f} ± {m_restored[\"ssim_std\"]:.4f}')\n"
        "print(f'\\nGAIN PSNR : {m_restored[\"psnr_mean\"] - m_degraded[\"psnr_mean\"]:+.2f} dB')\n"
        "print(f'GAIN SSIM : {m_restored[\"ssim_mean\"] - m_degraded[\"ssim_mean\"]:+.4f}')"
    ),
    md(
        "## 11. Étude — robustesse à différents niveaux de dégradation\n\n"
        "Le modèle a été entraîné sur facteur=4. Comment se comporte-t-il sur des dégradations plus ou moins fortes ?"
    ),
    code(
        "factors_test = [2, 3, 4, 6, 8]\n"
        "study = []\n"
        "for f in factors_test:\n"
        "    X_lo_f = degrade_resolution(X_test, f)\n"
        "    X_rest_f = unet.predict(X_lo_f, batch_size=BATCH_SIZE, verbose=0)\n"
        "    m_lo = compute_metrics(X_test, X_lo_f)\n"
        "    m_rest = compute_metrics(X_test, X_rest_f)\n"
        "    study.append({\n"
        "        'factor': f,\n"
        "        'psnr_degraded': m_lo['psnr_mean'],\n"
        "        'psnr_restored': m_rest['psnr_mean'],\n"
        "        'gain_psnr': m_rest['psnr_mean'] - m_lo['psnr_mean'],\n"
        "        'ssim_degraded': m_lo['ssim_mean'],\n"
        "        'ssim_restored': m_rest['ssim_mean'],\n"
        "        'gain_ssim': m_rest['ssim_mean'] - m_lo['ssim_mean'],\n"
        "    })\n"
        "df_study = pd.DataFrame(study)\n"
        "df_study"
    ),
    code(
        "fig, axes = plt.subplots(1, 2, figsize=(14, 4))\n"
        "axes[0].plot(df_study['factor'], df_study['psnr_degraded'], 'o-', label='dégradé (avant)')\n"
        "axes[0].plot(df_study['factor'], df_study['psnr_restored'], 's-', label='restauré (U-Net)')\n"
        "axes[0].axvline(DOWNSCALE_FACTOR_TRAIN, color='gray', linestyle='--', alpha=0.5, label='facteur entraînement')\n"
        "axes[0].set_xlabel('Facteur de downsampling'); axes[0].set_ylabel('PSNR (dB)')\n"
        "axes[0].set_title('PSNR vs facteur'); axes[0].legend(); axes[0].grid(True, alpha=0.3)\n\n"
        "axes[1].plot(df_study['factor'], df_study['ssim_degraded'], 'o-', label='dégradé (avant)')\n"
        "axes[1].plot(df_study['factor'], df_study['ssim_restored'], 's-', label='restauré (U-Net)')\n"
        "axes[1].axvline(DOWNSCALE_FACTOR_TRAIN, color='gray', linestyle='--', alpha=0.5, label='facteur entraînement')\n"
        "axes[1].set_xlabel('Facteur de downsampling'); axes[1].set_ylabel('SSIM')\n"
        "axes[1].set_title('SSIM vs facteur'); axes[1].legend(); axes[1].grid(True, alpha=0.3)\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ),
    md(
        "## 12. Étude — application aux images réelles du dataset (sans dégradation synthétique)\n\n"
        "**Le test le plus utile** : on passe les images **originales** du dataset (déjà basse résolution) "
        "directement dans le modèle, sans ajouter de dégradation synthétique. Le modèle a appris à 'sharpen' "
        "des images dégradées — sur les originales, il devrait quand même apporter un peu d'amélioration "
        "perceptuelle (les détails que le modèle imagine).\n\n"
        "On ne peut pas mesurer PSNR/SSIM ici (pas de référence HR), uniquement comparer visuellement."
    ),
    code(
        "# On prend quelques images du test set, on les passe directement sans dégradation\n"
        "X_orig_restored = unet.predict(X_test, batch_size=BATCH_SIZE, verbose=1)\n\n"
        "n = 6\n"
        "fig, axes = plt.subplots(n, 2, figsize=(8, 3 * n))\n"
        "for i in range(n):\n"
        "    axes[i, 0].imshow(X_test[i]); axes[i, 0].set_title('original dataset'); axes[i, 0].axis('off')\n"
        "    axes[i, 1].imshow(np.clip(X_orig_restored[i], 0, 1)); axes[i, 1].set_title('passé dans U-Net'); axes[i, 1].axis('off')\n"
        "plt.suptitle('Application sur images réelles (pas de dégradation ajoutée)')\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ),
    md(
        "## 13. Conclusions\n\n"
        "**Résultats à remplir après run** :\n"
        "- Gain PSNR moyen : ___ dB ; gain SSIM : ___\n"
        "- Comportement vs facteur de dégradation : ___\n"
        "- Inspection visuelle sur les originales : amélioration perceptible / non / dépend des images\n\n"
        "**Choix techniques justifiés** :\n"
        "- **U-Net** (autoencodeur + skip connections) : indispensable pour la restauration d'image. "
        "Sans skip, l'autoencodeur classique perd les détails fins au bottleneck et produit des sorties floues.\n"
        "- **Dégradation par downsample+upsample bilinéaire** : simule le type de dégradation présent dans le "
        "dataset (perte de résolution). Aurait pu être combiné avec du bruit gaussien, de la compression JPEG, "
        "ou du flou pour une dégradation plus réaliste.\n"
        "- **Approche self-supervised** : seule option viable sans paires HR de référence. Limite : le modèle "
        "apprend à inverser un modèle de dégradation synthétique, pas forcément le modèle réel.\n"
        "- **MSE comme loss** : standard, simple, mais tendance au flou. **Perceptual loss** (VGG features) "
        "donnerait des résultats plus nets visuellement.\n\n"
        "**Limites** :\n"
        "- Le modèle n'a jamais vu de \"vraies\" dégradations (capteur, compression JPEG, scan…). Il extrapole.\n"
        "- Les détails restaurés sont *plausibles*, pas *exacts* : c'est de la **hallucination guidée** par "
        "l'apprentissage des statistiques d'images naturelles.\n"
        "- Sur des facteurs de dégradation très éloignés de l'entraînement, le modèle se dégrade.\n\n"
        "**Pistes d'amélioration** :\n"
        "- **Modèle de dégradation plus riche** (combiner downsampling + flou + bruit + compression JPEG pendant "
        "l'entraînement) -> approche \"BSRGAN-like\".\n"
        "- **Perceptual loss + GAN loss** (SRGAN, Real-ESRGAN) pour des images plus nettes, au prix d'une plus "
        "grande complexité d'entraînement.\n"
        "- **Sub-pixel convolution** (pixel shuffle) au lieu de UpSampling+Conv -> meilleurs résultats en SR.\n"
        "- **Entraînement plus long avec data augmentation** (flips, rotations) pour mieux généraliser.\n"
        "- **Évaluation human-eval** : SSIM/PSNR sont des proxys ; un test utilisateur dirait mieux si "
        "l'amélioration est perceptible."
    ),
]


if __name__ == '__main__':
    nb = nbf.v4.new_notebook()
    nb.cells = cells
    nb.metadata = {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10"},
    }
    path = OUTDIR / 'L2_super_resolution.ipynb'
    with open(path, 'w', encoding='utf-8') as f:
        nbf.write(nb, f)
    print(f'Écrit : {path}')
